######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 26 20:25:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lrt -lX11
CONFIG += qt debug
RESOURCES += files.qrc


# Input
HEADERS += popup.h QtKeygrab.h
SOURCES += popup.cpp QtKeygrab.cpp main.cpp
