######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 3 19:25:19 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += popup.h QtKeygrab.h
SOURCES += main.cpp popup.cpp QtKeygrab.cpp
RESOURCES += files.qrc
